### ISSUE TITLE
Improve the implementation of TurbViscosityStencil::apply for performance

### ISSUE THREAD

**Issue by MakisH** [klicperajo/turbulent#3]
One of the feedback points we got today was about the switch block in the `TurbViscosityStencil::apply` (file `stencils/TurbViscosityStencil.cpp`, line 35). This may affect the performance on some architectures (it would actually be interesting to measure that). Somehow we have to move the condition out of the stencil.

**Comment by tpaula** [comment]
Resolved with commit 95ef307ee9fbe058c8c9cd6a9b0d917d27b38eaf.
